#!/bin/bash

sudo apt-get install -y make
sudo apt-get install -y cmake
sudo apt-get install -y g++
sudo apt-get install -y wget
sudo apt-get install -y curl
sudo apt-get install -y automake
sudo apt-get install -y git
sudo apt-get install -y mpi
sudo apt-get install -y mpi-default-bin
sudo apt-get install -y mpi-default-dev
sudo apt-get install -y mpi-specs
sudo apt-get install -y mpich
sudo apt-get install -y openmpi-bin
sudo apt-get install -y openmpi-common
sudo apt-get install -y libopenmpi-dev
sudo apt-get install -y libopenmpi3
sudo apt-get install -y fftw-dev
sudo apt-get install -y fftw-single-dev
sudo apt-get install -y fftw-double-dev
sudo apt-get install -y fftw2
sudo apt-get install -y fftw2-single
sudo apt-get install -y fftw2-double
sudo apt-get install -y fftw3
sudo apt-get install -y fftw3-dev
sudo apt-get install -y libfftw3-3
sudo apt-get install -y libfftw3-bin
sudo apt-get install -y libfftw3-dev
sudo apt-get install -y libfftw3-double3
sudo apt-get install -y libfftw3-long3
sudo apt-get install -y libfftw3-mpi-dev
sudo apt-get install -y libfftw3-mpi3
sudo apt-get install -y libfftw3-quad3
sudo apt-get install -y libfftw3-single3
sudo apt-get install -y gzip
sudo apt-get install -y gzip-win32
sudo apt-get install -y libjpeg-dbg
sudo apt-get install -y libjpeg-dev
sudo apt-get install -y libjpeg-progs
sudo apt-get install -y libjpeg-tools
sudo apt-get install -y libjpeg-turbo-progs
sudo apt-get install -y libjpeg-turbo-test
sudo apt-get install -y libjpeg-turbo8
sudo apt-get install -y libjpeg-turbo8-dbg
sudo apt-get install -y libjpeg-turbo8-dev
sudo apt-get install -y libjpeg62
sudo apt-get install -y libjpeg62-dev
sudo apt-get install -y libjpeg8
sudo apt-get install -y libjpeg8-dbg
sudo apt-get install -y libjpeg8-dev
sudo apt-get install -y libjpeg9
sudo apt-get install -y libjpeg9-dev
sudo apt-get install -y libturbojpeg
sudo apt-get install -y libturbojpeg-dev
sudo apt-get install -y libturbojpeg0-dev
sudo apt-get install -y libpng++-dev
sudo apt-get install -y libpng-dev
sudo apt-get install -y libpng-tools
sudo apt-get install -y libpng16-16
sudo apt-get install -y libpnglite-dev
sudo apt-get install -y libpnglite0
sudo apt-get install -y png-definitive-guide
sudo apt-get install -y png23d
sudo apt-get install -y png2html
sudo apt-get install -y pngcheck
sudo apt-get install -y pngcrush
sudo apt-get install -y pngmeta
sudo apt-get install -y pngnq
sudo apt-get install -y pngquant
sudo apt-get install -y pngtools
sudo apt-get install -y ffmpeg
sudo apt-get install -y ffmpeg-doc
sudo apt-get install -y ffmpeg2theora
sudo apt-get install -y ffmpegfs
sudo apt-get install -y ffmpegthumbnailer
sudo apt-get install -y ffmpegthumbs
sudo apt-get install -y libadios-*
sudo apt-get install -y python3
sudo apt-get install -y python3-dev
sudo apt-get install -y python3-adios
sudo apt-get install -y zlib-gst
sudo apt-get install -y zlib1g
sudo apt-get install -y zlib1g-dev
sudo apt-get install -y libzstd-dev
sudo apt-get install -y libzstd1
sudo apt-get install -y tar
sudo apt-get install -y zip
sudo apt-get install -y wget
sudo apt-get install -y libadios-mpich-dev
sudo apt-get install -y libadios-openmpi-dev
sudo apt-get install -y liblapack-dev
sudo apt-get install -y liblapack-doc
sudo apt-get install -y liblapack-pic
sudo apt-get install -y liblapack-test
sudo apt-get install -y liblapack3
sudo apt-get install -y liblapack64-3
sudo apt-get install -y liblapack64-dev
sudo apt-get install -y liblapack64-test
sudo apt-get install -y liblapacke
sudo apt-get install -y liblapacke-dev
sudo apt-get install -y liblapacke64
sudo apt-get install -y liblapacke64-dev
sudo apt-get install -y libblas-dev
sudo apt-get install -y libblas-test
sudo apt-get install -y libblas3
sudo apt-get install -y libblas64-3
sudo apt-get install -y libblas64-dev
sudo apt-get install -y libblas64-test
sudo apt-get install -y libblasr-dev
sudo apt-get install -y libblis-dev
sudo apt-get install -y libblis-openmp-dev
sudo apt-get install -y libblis-pthread-dev
sudo apt-get install -y libblis-serial-dev
sudo apt-get install -y libblis3
sudo apt-get install -y libblis3-openmp
sudo apt-get install -y libblis3-pthread
sudo apt-get install -y libblis3-serial
sudo apt-get install -y libblis64-3
sudo apt-get install -y libblis64-3-openmp
sudo apt-get install -y libblis64-3-pthread
sudo apt-get install -y libblis64-3-serial
sudo apt-get install -y libblis64-dev
sudo apt-get install -y libblis64-openmp-dev
sudo apt-get install -y libblis64-pthread-dev
sudo apt-get install -y libblis64-serial-dev
sudo apt-get install -y libbliss
sudo apt-get install -y libbliss-dev
sudo apt-get install -y libbliss-dev-common
sudo apt-get install -y libbliss2
sudo apt-get install -y calibre
sudo apt-get install -y vokoscreen
sudo apt-get install -y exuberant-ctags
sudo apt-get install -y gedit-common
sudo apt-get install -y gedit-dev
sudo apt-get install -y gedit-latex-plugin
sudo apt-get install -y gedit-plugin-bookmarks
sudo apt-get install -y gedit-plugin-bracket-completion
sudo apt-get install -y gedit-plugin-character-map
sudo apt-get install -y gedit-plugin-code-comment
sudo apt-get install -y gedit-plugin-color-picker
sudo apt-get install -y gedit-plugin-color-schemer
sudo apt-get install -y gedit-plugin-commander
sudo apt-get install -y gedit-plugin-draw-spaces
sudo apt-get install -y gedit-plugin-find-in-files
sudo apt-get install -y gedit-plugin-git
sudo apt-get install -y gedit-plugin-join-lines
sudo apt-get install -y gedit-plugin-multi-edit
sudo apt-get install -y gedit-plugin-session-saver
sudo apt-get install -y gedit-plugin-smart-spaces
sudo apt-get install -y gedit-plugin-synctex
sudo apt-get install -y gedit-plugin-terminal
sudo apt-get install -y gedit-plugin-text-size
sudo apt-get install -y gedit-plugin-translate
sudo apt-get install -y gedit-plugin-word-completion
sudo apt-get install -y gedit-plugins
sudo apt-get install -y gedit-plugins-common
sudo apt-get install -y gedit-source-code-browser-plugin
sudo apt-get install -y chktex
